language: node_js
node_js:
- 7
script:
- npm test

env:
  global:
  - BX_APP=your-celebrity-match
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos

before_deploy: npm install -g bx-blue-green
deploy:
  skip_cleanup: true
  provider: script
  script:
  - bx-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/your-celebrity-match
notifications:
  email: false
